//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 YX_TEST3_2.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_YX_TEST3_2TYPE              130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define ID_VIEW_OUTPUTWND               220
#define IDR_OUTPUT_POPUP                221
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_MENU1                       310
#define IDD_INFO                        311
#define IDB_BITMAP1                     311
#define IDB_BITMAP5                     312
#define IDB_BITMAP10                    313
#define IDB_BITMAP20                    314
#define IDB_BITMAP11                    315
#define IDB_BITMAP12                    316
#define IDB_BITMAP13                    317
#define IDB_BITMAP14                    318
#define IDB_BITMAP15                    319
#define IDB_BITMAP16                    320
#define IDB_BITMAP17                    321
#define IDB_BITMAP18                    322
#define IDB_BITMAP19                    323
#define IDB_BITMAP2                     324
#define IDB_BITMAP3                     325
#define IDB_BITMAP4                     326
#define IDB_BITMAP6                     327
#define IDB_BITMAP7                     328
#define IDB_BITMAP8                     329
#define IDB_BITMAP9                     330
#define IDD_DIALOG1                     331
#define IDC_DATETIMEPICKER1             1001
#define IDC_CLASS                       1002
#define IDC_INSERT_NAME                 1003
#define IDC_INSERT_ID                   1004
#define IDC_EDIT4                       1005
#define IDC_INSERT_OTHER                1005
#define IDC_INSERT_SEX                  1006
#define ID_32771                        32771
#define ID_SHOW_PHOTOS                  32772
#define ID_32773                        32773
#define ID_SHOW_INFO                    32774
#define ID_INFO_LIST                    53574
#define ID_INFO_NAME                    53575
#define ID_INFO_CLASS                   53576
#define ID_INFO_ID                      53577
#define ID_INFO_DATE                    53578
#define ID_INFO_OTHER                   53579
#define ID_INFO_SEX                     53580
#define ID_INFO_INSERT                  53581
#define ID_INFO_MODIFY                  53582
#define ID_INFO_DELETE                  53583

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        332
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1007
#define _APS_NEXT_SYMED_VALUE           312
#endif
#endif
